export const occasionCakes = [
  { src: "oc1.jpg", alt: "occational cakes" },
  { src: "oc2.jpg", alt: "occational cakes" },
  { src: "oc3.jpg", alt: "occational cakes" },
  { src: "oc4.jpg", alt: "occational cakes" },
  { src: "oc5.jpg", alt: "occational cakes" },
  { src: "oc6.jpg", alt: "occational cakes" },
  { src: "oc7.jpg", alt: "occational cakes" },
  { src: "oc8.jpg", alt: "occational cakes" },
  { src: "oc9.jpg", alt: "occational cakes" },
  { src: "oc10.jpg", alt: "occational cakes" },
  { src: "oc11.jpg", alt: "occational cakes" },
  { src: "oc12.jpg", alt: "occational cakes" },
  { src: "oc13.jpg", alt: "occational cakes" },
  { src: "oc14.jpg", alt: "occational cakes" },
  { src: "oc15.jpg", alt: "occational cakes" },
  { src: "oc16.jpg", alt: "occational cakes" },
  { src: "oc17.jpg", alt: "occational cakes" },
  { src: "oc18.jpg", alt: "occational cakes" },
  { src: "oc19.jpg", alt: "occational cakes" },
  { src: "oc20.jpg", alt: "occational cakes" },
  { src: "oc21.jpg", alt: "occational cakes" },
  { src: "oc22.jpg", alt: "occational cakes" },
  { src: "oc23.jpg", alt: "occational cakes" },
  { src: "oc24.jpg", alt: "occational cakes" },
  { src: "oc25.jpg", alt: "occational cakes" },
  { src: "oc26.jpg", alt: "occational cakes" },
  { src: "oc27.jpg", alt: "occational cakes" },
  { src: "oc28.jpg", alt: "occational cakes" },
  { src: "oc29.jpg", alt: "occational cakes" },
  { src: "oc30.jpg", alt: "occational cakes" },
  { src: "oc31.jpg", alt: "occational cakes" },
  { src: "oc32.jpg", alt: "occational cakes" },
  { src: "oc33.jpg", alt: "occational cakes" },
];
export const cheesecakes = [
  { src: "cc1.jpg", alt: "cheesecake" },
  { src: "cc2.jpg", alt: "cheesecake" },
  { src: "cc3.jpg", alt: "cheesecake" },
  { src: "cc4.jpg", alt: "cheesecake" },
  { src: "cc5.jpg", alt: "cheesecake" },
  { src: "cc6.jpg", alt: "cheesecake" },
  { src: "cc7.jpg", alt: "cheesecake" },
  { src: "cc8.jpg", alt: "cheesecake" },
  { src: "cc9.jpg", alt: "cheesecake" },
  { src: "cc10.jpg", alt: "cheesecake" },
  { src: "cc11.jpg", alt: "cheesecake" },
  { src: "cc12.jpg", alt: "cheesecake" },
  { src: "cc13.jpg", alt: "cheesecake" },
  { src: "cc14.jpg", alt: "cheesecake" },
  { src: "cc15.jpg", alt: "cheesecake" },
  { src: "cc16.jpg", alt: "cheesecake" },
  { src: "cc17.jpg", alt: "cheesecake" },
  { src: "cc18.jpg", alt: "cheesecake" },
  { src: "cc19.jpg", alt: "cheesecake" },
  { src: "cc10.jpg", alt: "cheesecake" },
  { src: "cc20.jpg", alt: "cheesecake" },
  { src: "cc21.jpg", alt: "cheesecake" },
];
export const basicCakes = [
  { src: "bc1.jpg", alt: "basic cake" },
  { src: "bc2.jpg", alt: "basic cake" },
  { src: "bc3.jpg", alt: "basic cake" },
  { src: "bc4.jpg", alt: "basic cake" },
  { src: "bc5.jpg", alt: "basic cake" },
  { src: "bc6.jpg", alt: "basic cake" },
  { src: "bc7.jpg", alt: "basic cake" },
  { src: "bc8.jpg", alt: "basic cake" },
];
export const others = [
  { src: "o1.jpg", alt: "other items" },
  { src: "o2.jpg", alt: "other items" },
  { src: "o3.jpg", alt: "other items" },
  { src: "o4.jpg", alt: "other items" },
  { src: "o5.jpg", alt: "other items" },
  { src: "o6.jpg", alt: "other items" },
  { src: "o7.jpg", alt: "other items" },
  { src: "o8.jpg", alt: "other items" },
  { src: "o9.jpg", alt: "other items" },
  { src: "o10.jpg", alt: "other items" },
  { src: "o11.jpg", alt: "other items" },
  { src: "o12.jpg", alt: "other items" },
  { src: "o13.jpg", alt: "other items" },
  { src: "o14.jpg", alt: "other items" },
  { src: "o15.jpg", alt: "other items" },
  { src: "o16.jpg", alt: "other items" },
  { src: "o17.jpg", alt: "other items" },
  { src: "o18.jpg", alt: "other items" },
  { src: "o19.jpg", alt: "other items" },
  { src: "o20.jpg", alt: "other items" },
  { src: "o21.jpg", alt: "other items" },
];
